name: "Jest Tests"

on:
  push:
    branches: [ "master", "buff-address-bar-search" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: pnpm ci
      - run: pnpm test
