name: "Jest Tests"

on:
  push:
    branches: [ "master", "buff-address-bar-search" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: CI=true pnpm i # see: https://stackoverflow.com/a/75486166/6920681
      - run: pnpm test
